name: Deploy Docs
run-name: ${{ format('{0} ({1})', github.workflow, github.event.inputs.build-refname || 'all') }}
on:
  workflow_dispatch:
    inputs:
      build-refname:
        description: Enter git refname to build (e.g., 5.7.x).
        required: false
  push:
    branches: docs-build
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up refname build
      if: github.event.inputs.build-refname
      run: |
        echo ${{ github.event.inputs.build-refname }}
    - name: Run Antora
      run: echo 'Run Antora'
